# 06/09/2019
# Feature Selection:

In [1]:
import pandas as pd
import numpy as np


In [2]:
data= pd.read_csv("E:/Neha Python/diabetes.csv")

In [4]:
Y=data.drop(['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age'],axis=1)
Y

Outcome
0          1
1          0
2          1
3          0
4          1
5          0
6          1
7          0
8          1
9          1
10         0
11         1
12         0
13         1
14         1
15         1
16         1
17         1
18         0
19         1
20         0
21         0
22         1
23         1
24         1
25         1
26         1
27         0
28         0
29         0
..       ...
738        0
739        1
740        1
741        0
742        0
743        1
744        0
745        0
746        1
747        0
748        1
749        1
750        1
751        0
752        0
753        1
754        1
755        1
756        0
757        1
758        0
759        1
760        0
761        1
762        0
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [5]:
X=data.drop(['Outcome'],axis=1)
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [6]:
# Or we can write X and Y as follows:
array=data.values
X=array[:,0:8]
Y=array[:,8]

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [9]:
#Import the necesary libraries
from sklearn.feature_selection import SelectKBest # sklearn is for scikit
from sklearn.feature_selection import chi2 # to chek mean sq. error (R^2) calculation

In [10]:
# Feature Extraction:
test=SelectKBest(score_func=chi2, k=4)  # k=4 means select 4 best field
fit=test.fit(X,Y)   #Summarize scores
np.set_printoptions(precision=3) # precision 3 means again 3 best fields are chosen

print(fit.scores_)


# now here it will shoe the p values for all 8 fields. And from that it will select the fields having maximum values 
#with descending order. Now in this max values are 2175.565,1411.887 ,181.304, 111.52  are the max value 4 fields are selected 
# now see index of those fields in table. It will be glucose, insuline, etc....

In [11]:
features=fit.transform(X) # Due to precision =3 it is giving only 3 columns out of best 4
print(features)

[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 ...
 [121.  112.   26.2  30. ]
 [126.    0.   30.1  47. ]
 [ 93.    0.   30.4  23. ]]


In [12]:
# summarize selected features
print(features[0:5,:])# Import your necessary dependencies

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]


In [13]:
# Import your necessary dependencies

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


In [14]:
# Feature Extraction
model=LogisticRegression()
rfe=RFE(model,3) # Again select 3 best fildes (or take number of fields how many required)
fit=rfe.fit(X,Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_)) # will give true for field which is selected
print("Feature Ranking: %s" % (fit.ranking_)) # Gives rank according to selection (by p value) 
#It will give rank 1 which is to be selected

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Num Features: 3
Selected Features: [ True False False False False  True  True False]
Feature Ranking: [1 2 3 5 6 1 1 4]


C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

In [ ]:
# The above method is manual as we define precision=3 means we define best fields to be selected
# Now above proceure can be done by using OLS to get best fields automatically depending on p-values as follows:


from sklearn.feature_selection import RFE  #(RFE- Recursive Forward Elemination)
from sklearn.linear_model import LogisticRegression
# OLs model is best as it utomatically gives bests fields based on p values

In [15]:
import statsmodels.api as sm


In [16]:
X1=sm.add_constant(X)  # X is Defined above which is fields except outcomes 

X1

array([[  1.   ,   6.   , 148.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,   1.   ,  85.   , ...,  26.6  ,   0.351,  31.   ],
       [  1.   ,   8.   , 183.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  1.   ,   5.   , 121.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   ,   1.   , 126.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,   1.   ,  93.   , ...,  30.4  ,   0.315,  23.   ]])

In [17]:
model=sm.OLS(Y,X1).fit()  # Y is defined above which is Outcomes

In [18]:
model.summary()

# In summary table take those fields whose p value is less than 0.05----

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.303
Model:                            OLS   Adj. R-squared:                  0.296
Method:                 Least Squares   F-statistic:                     41.29
Date:                Wed, 11 Sep 2019   Prob (F-statistic):           7.36e-55
Time:                        18:53:35   Log-Likelihood:                -381.91
No. Observations:                 768   AIC:                             781.8
Df Residuals:                     759   BIC:                             823.6
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.8539      0.085     -9.989      0.000      -1.022      -0.686
x1             0.0206      0.005      4.014      0.000       0.011       0.031
x2             0.0059      0.001     11.493      0.000       0.005       0.007
x3            -0.0023      0.001     -2.873      0.004      -0.004      -0.001
x4             0.0002      0.001      0.139      0.890      -0.002       0.002
x5            -0.0002      0.000     -1.205      0.229      -0.000       0.000
x6             0.0132      0.002      6.344      0.000       0.009       0.017
x7             0.1472      0.045      3.268      0.001       0.059       0.236
x8             0.0026      0.002      1.693      0.091      -0.000       0.006
==============================================================================
Omnibus:                       41.539   Durbin-Watson:                   1.982
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               31.183
Skew:                           0.395   Prob(JB):                     1.69e-07
Kurtosis:                       2.408   Cond. No.                     1.10e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.1e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""