In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest # K= number of required feature
from sklearn.feature_selection import chi2  # Chi will discover value of each x related to y

In [2]:
df=pd.read_csv("E:/Neha Python/Machin Learning Notes/train2.csv")

In [3]:
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
5              1859     0          0.5         1   3       0          22   
6              1821     0          1.7         0   4       1          10   
7              1954     0          0.5         1   0       0          24   
8              1445     1          0.5         0   0       0          53   
9               509     1          0.6         1   2       1           9   
10              769     1          2.9         1   0       0           9   
11             1520     1          2.2         0   5       1          33   
12             1815     0          2.8         0   2       0          33   
13              803     1          2.1         0   7       0          17   
14             1866     0          0.5         0  13       1          52   
15              775     0          1.0         0   3       0          46   
16              838     0          0.5         0   1       1          13   
17              595     0          0.9         1   7       1          23   
18             1131     1          0.5         1  11       0          49   
19              682     1          0.5         0   4       0          19   
20              772     0          1.1         1  12       0          39   
21             1709     1          2.1         0   1       0          13   
22             1949     0          2.6         1   4       0          47   
23             1602     1          2.8         1   4       1          38   
24              503     0          1.2         1   5       1           8   
25              961     1          1.4         1   0       1          57   
26              519     1          1.6         1   7       1          51   
27              956     0          0.5         0   1       1          41   
28             1453     0          1.6         1  12       1          52   
29              851     0          0.5         0   3       0          21   
...             ...   ...          ...       ...  ..     ...         ...   
1970           1913     1          1.8         0   0       0          29   
1971            538     0          1.1         1   0       1          25   
1972           1191     0          0.8         0   6       1          46   
1973            816     0          3.0         1   2       0           9   
1974            915     1          0.5         1   9       1          33   
1975           1157     1          0.8         0   7       0          27   
1976           1201     1          0.5         0   2       0          10   
1977           1379     0          1.1         1   1       1          18   
1978           1483     1          2.2         0   3       1          53   
1979           1614     0          1.2         0   1       1           9   
1980            930     1          1.0         1   4       1           4   
1981           1454     0          2.6         0   8       0           6   
1982           1784     0          1.6         0   4       0          41   
1983           1262     0          1.8         1  12       0          34   
1984            797     0          2.2         1   0       0          37   
1985           1829     1          2.1         0   8       0          59   
1986           1139     1          0.9         1   6       1          58   
1987            618     1          1.0         0   9       1          13   
1988           1547     1          2.9         0   2       0          57   
1989            586     0          2.8         0   2       0          15   
1990           1617     1          2.4         0   8  

In [5]:
x=df.iloc[:,0:20]# independant columns
x

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
5              1859     0          0.5         1   3       0          22   
6              1821     0          1.7         0   4       1          10   
7              1954     0          0.5         1   0       0          24   
8              1445     1          0.5         0   0       0          53   
9               509     1          0.6         1   2       1           9   
10              769     1          2.9         1   0       0           9   
11             1520     1          2.2         0   5       1          33   
12             1815     0          2.8         0   2       0          33   
13              803     1          2.1         0   7       0          17   
14             1866     0          0.5         0  13       1          52   
15              775     0          1.0         0   3       0          46   
16              838     0          0.5         0   1       1          13   
17              595     0          0.9         1   7       1          23   
18             1131     1          0.5         1  11       0          49   
19              682     1          0.5         0   4       0          19   
20              772     0          1.1         1  12       0          39   
21             1709     1          2.1         0   1       0          13   
22             1949     0          2.6         1   4       0          47   
23             1602     1          2.8         1   4       1          38   
24              503     0          1.2         1   5       1           8   
25              961     1          1.4         1   0       1          57   
26              519     1          1.6         1   7       1          51   
27              956     0          0.5         0   1       1          41   
28             1453     0          1.6         1  12       1          52   
29              851     0          0.5         0   3       0          21   
...             ...   ...          ...       ...  ..     ...         ...   
1970           1913     1          1.8         0   0       0          29   
1971            538     0          1.1         1   0       1          25   
1972           1191     0          0.8         0   6       1          46   
1973            816     0          3.0         1   2       0           9   
1974            915     1          0.5         1   9       1          33   
1975           1157     1          0.8         0   7       0          27   
1976           1201     1          0.5         0   2       0          10   
1977           1379     0          1.1         1   1       1          18   
1978           1483     1          2.2         0   3       1          53   
1979           1614     0          1.2         0   1       1           9   
1980            930     1          1.0         1   4       1           4   
1981           1454     0          2.6         0   8       0           6   
1982           1784     0          1.6         0   4       0          41   
1983           1262     0          1.8         1  12       0          34   
1984            797     0          2.2         1   0       0          37   
1985           1829     1          2.1         0   8       0          59   
1986           1139     1          0.9         1   6       1          58   
1987            618     1          1.0         0   9       1          13   
1988           1547     1          2.9         0   2       0          57   
1989            586     0          2.8         0   2       0          15   
1990           1617     1          2.4         0   8  

In [7]:
y=df.iloc[:,20]
y

0       1
1       2
2       2
3       2
4       1
5       1
6       3
7       0
8       0
9       0
10      3
11      3
12      1
13      2
14      0
15      0
16      3
17      3
18      1
19      1
20      3
21      3
22      1
23      0
24      1
25      2
26      3
27      3
28      2
29      0
       ..
1970    2
1971    1
1972    0
1973    3
1974    1
1975    3
1976    0
1977    2
1978    1
1979    1
1980    1
1981    1
1982    2
1983    2
1984    1
1985    3
1986    1
1987    0
1988    1
1989    1
1990    0
1991    3
1992    0
1993    3
1994    3
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [16]:
# Feature Extraction:
test=SelectKBest(score_func=chi2, k=4)  # k=4 means select 4 best field
fit=test.fit(x,y)   

In [17]:
#Summarize scores
np.set_printoptions(precision=3) # precision 3 means again 3 best fields are chosen

print(fit.scores_)


# now here it will shoe the p values for all 8 fields. And from that it will select the fields having maximum values 
#with descending order. Now in this max values are 2175.565,1411.887 ,181.304, 111.52  are the max value 4 fields are selected 
# now see index of those fields in table. It will be glucose, insuline, etc....

[1.413e+04 7.232e-01 6.484e-01 6.310e-01 1.014e+01 1.522e+00 8.984e+01
 7.458e-01 9.597e+01 9.098e+00 9.186e+00 1.736e+04 9.811e+03 9.313e+05
 9.615e+00 1.648e+01 1.324e+01 3.276e-01 1.928e+00 4.221e-01]


In [19]:
features=fit.transform(x) # Due to precision =3 it is giving only 3 columns out of best 4
print(features)

[[ 842.   20.  756. 2549.]
 [1021.  905. 1988. 2631.]
 [ 563. 1263. 1716. 2603.]
 ...
 [1911.  868. 1632. 3057.]
 [1512.  336.  670.  869.]
 [ 510.  483.  754. 3919.]]


In [20]:
# summarize selected features
print(features[0:5,:])

[[ 842.   20.  756. 2549.]
 [1021.  905. 1988. 2631.]
 [ 563. 1263. 1716. 2603.]
 [ 615. 1216. 1786. 2769.]
 [1821. 1208. 1212. 1411.]]


In [21]:
# Import your necessary dependencies

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


In [23]:
# Feature Extraction
model=LogisticRegression()
rfe=RFE(model,3) # Again select 3 best fildes (or take number of fields how many required)
fit=rfe.fit(x,y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_)) # will give true for field which is selected
print("Feature Ranking: %s" % (fit.ranking_)) # Gives rank according to selection (by p value) 
#It will give rank 1 which is to be selected

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver 

Num Features: 3
Selected Features: [False False False False False  True False  True False False False False
 False False False False False  True False False]
Feature Ranking: [16  3  6  4 11  1 13  1 14  7 12 17 18 15  8  9 10  1  2  5]


C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver 

In [28]:
import statsmodels.api as sm

In [29]:
X1=sm.add_constant(x)  # X is Defined above which is fields except outcomes 

X1

C:\Users\Asus\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


const  battery_power  blue  clock_speed  dual_sim  fc  four_g  \
0       1.0            842     0          2.2         0   1       0   
1       1.0           1021     1          0.5         1   0       1   
2       1.0            563     1          0.5         1   2       1   
3       1.0            615     1          2.5         0   0       0   
4       1.0           1821     1          1.2         0  13       1   
5       1.0           1859     0          0.5         1   3       0   
6       1.0           1821     0          1.7         0   4       1   
7       1.0           1954     0          0.5         1   0       0   
8       1.0           1445     1          0.5         0   0       0   
9       1.0            509     1          0.6         1   2       1   
10      1.0            769     1          2.9         1   0       0   
11      1.0           1520     1          2.2         0   5       1   
12      1.0           1815     0          2.8         0   2       0   
13      1.0            803     1          2.1         0   7       0   
14      1.0           1866     0          0.5         0  13       1   
15      1.0            775     0          1.0         0   3       0   
16      1.0            838     0          0.5         0   1       1   
17      1.0            595     0          0.9         1   7       1   
18      1.0           1131     1          0.5         1  11       0   
19      1.0            682     1          0.5         0   4       0   
20      1.0            772     0          1.1         1  12       0   
21      1.0           1709     1          2.1         0   1       0   
22      1.0           1949     0          2.6         1   4       0   
23      1.0           1602     1          2.8         1   4       1   
24      1.0            503     0          1.2         1   5       1   
25      1.0            961     1          1.4         1   0       1   
26      1.0            519     1          1.6         1   7       1   
27      1.0            956     0          0.5         0   1       1   
28      1.0           1453     0          1.6         1  12       1   
29      1.0            851     0          0.5         0   3       0   
...     ...            ...   ...          ...       ...  ..     ...   
1970    1.0           1913     1          1.8         0   0       0   
1971    1.0            538     0          1.1         1   0       1   
1972    1.0           1191     0          0.8         0   6       1   
1973    1.0            816     0          3.0         1   2       0   
1974    1.0            915     1          0.5         1   9       1   
1975    1.0           1157     1          0.8         0   7       0   
1976    1.0           1201     1          0.5         0   2       0   
1977    1.0           1379     0          1.1         1   1       1   
1978    1.0           1483     1          2.2         0   3       1   
1979    1.0           1614     0          1.2         0   1       1   
1980    1.0            930     1          1.0         1   4       1   
1981    1.0           1454     0          2.6         0   8       0   
1982    1.0           1784     0          1.6         0   4       0   
1983    1.0           1262     0          1.8         1  12       0   
1984    1.0            797     0          2.2         1   0       0   
1985    1.0           1829     1          2.1         0   8       0   
1986    1.0           1139     1          0.9         1   6       1   
1987    1.0            618     1          1.0         0   9       1   
1988    1.0           1547     1          2.9         0   2       0   
1989    1.0            586     0          2.8         0   2       0   
1990    1.0           1617     1          2.4         0   8       1   
1991    1.0           1882     0          2.0         0  11       1   
1992    1.0            674     1          2.9         1   1       0   
1993    1.0           1467     1          0.5         0   0       0   
1994    1.0            858    

In [30]:
model=sm.OLS(y,X1).fit()  # y is defined above which is Outcomes

In [31]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:            price_range   R-squared:                       0.919
Model:                            OLS   Adj. R-squared:                  0.918
Method:                 Least Squares   F-statistic:                     1117.
Date:                Wed, 18 Sep 2019   Prob (F-statistic):               0.00
Time:                        19:25:54   Log-Likelihood:                -552.26
No. Observations:                2000   AIC:                             1147.
Df Residuals:                    1979   BIC:                             1264.
Df Model:                          20                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -1.5750      0.062    -25.553      0.000      -1.696      -1.454
battery_power     0.0005   1.64e-05     31.071      0.000       0.000       0.001
blue             -0.0020      0.014     -0.141      0.888      -0.030       0.026
clock_speed      -0.0121      0.009     -1.368      0.171      -0.029       0.005
dual_sim         -0.0237      0.014     -1.644      0.100      -0.052       0.005
fc                0.0009      0.002      0.432      0.666      -0.003       0.005
four_g           -0.0015      0.018     -0.083      0.934      -0.036       0.033
int_memory        0.0009      0.000      2.178      0.030    8.61e-05       0.002
m_dep            -0.0100      0.025     -0.399      0.690      -0.059       0.039
mobile_wt        -0.0009      0.000     -4.335      0.000      -0.001      -0.000
n_cores           0.0018      0.003      0.579      0.563      -0.004       0.008
pc                0.0001      0.002      0.083      0.934      -0.003       0.003
px_height         0.0003   1.89e-05     14.626      0.000       0.000       0.000
px_width          0.0003   1.94e-05     14.437      0.000       0.000       0.000
ram               0.0009   6.64e-06    142.688      0.000       0.001       0.001
sc_h              0.0011      0.002      0.575      0.565      -0.003       0.005
sc_w             -0.0003      0.002     -0.171      0.864      -0.004       0.003
talk_time         0.0004      0.001      0.276      0.783      -0.002       0.003
three_g           0.0270      0.021      1.301      0.193      -0.014       0.068
touch_screen     -0.0057      0.014     -0.397      0.691      -0.034       0.022
wifi             -0.0214      0.014     -1.489      0.137      -0.050       0.007
==============================================================================
Omnibus:                      114.748   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               43.786
Skew:                           0.038   Prob(JB):                     3.10e-10
Kurtosis:                       2.279   Cond. No.                     2.58e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.58e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [37]:
x_modif=df[['battery_power','int_memory','mobile_wt','px_height','px_width','ram']]
x_modif

battery_power  int_memory  mobile_wt  px_height  px_width   ram
0               842           7        188         20       756  2549
1              1021          53        136        905      1988  2631
2               563          41        145       1263      1716  2603
3               615          10        131       1216      1786  2769
4              1821          44        141       1208      1212  1411
5              1859          22        164       1004      1654  1067
6              1821          10        139        381      1018  3220
7              1954          24        187        512      1149   700
8              1445          53        174        386       836  1099
9               509           9         93       1137      1224   513
10              769           9        182        248       874  3946
11             1520          33        177        151      1005  3826
12             1815          33        159        607       748  1482
13              803          17        198        344      1440  2680
14             1866          52        185        356       563   373
15              775          46        159        862      1864   568
16              838          13        196        984      1850  3554
17              595          23        121        441       810  3752
18             1131          49        101        658       878  1835
19              682          19        121        902      1064  2337
20              772          39         81       1314      1854  2819
21             1709          13        156        974      1385  3283
22             1949          47        199        407       822  1433
23             1602          38        114        466       788  1037
24              503           8        111        201      1245  2583
25              961          57        114        291      1434  2782
26              519          51        132        550       645  3763
27              956          41        143        511      1075  3286
28             1453          52         96        187      1311  2373
29              851          21        200       1171      1263   478
...             ...         ...        ...        ...       ...   ...
1970           1913          29        111        675       742  2023
1971            538          25        163        455       537  2215
1972           1191          46         89         42       807   824
1973            816           9        117       1196      1651  3851
1974            915          33        199        503       986  2156
1975           1157          27         88       1694      1798  2885
1976           1201          10         99        306       558   495
1977           1379          18        129        838       885  2358
1978           1483          53        169        291       651  1744
1979           1614           9        161        173      1219  1832
1980            930           4        144       1017      1289  2016
1981           1454           6        199        698      1018  1300
1982           1784          41        164        610      1437  2313
1983           1262          34        149        223       737  3248
1984            797          37        144        206      1167  2216
1985           1829          59         91       1457      1919  3142
1986           1139          58        161        742       999  1850
1987            618          13         80        591       724  1424
1988           1547          57        114        347       957  1620
1989            586          15         83        241       854  2592
1990           1617          36         85        743      1426   296
1991           1882          44        113          4       743  3579
1992            674          21        198        576      1809  1180
1993           1467          18        122        888      1099  3962
1994            858          50         84        528      1416  3978
1995            

In [51]:
(x_train,x_test,y_train,y_test) = train_test_split(x_modif, y, test_size=25, random_state=0)

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train =sc.fit_transform(x_train)
x_test =sc.transform(x_test)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [45]:
model = LogisticRegression()

In [46]:
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [47]:
y_pred =classifier.predict(x_test)

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
accuracy_score(y_test, y_pred)

0.8