# Example of wine quality test


In [1]:
import pandas as pd
import numpy as np

In [2]:
D1= pd.read_csv("E:/Neha Python/wineQualityReds.csv")
D1.head()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0           1            7.4              0.70         0.00             1.9   
1           2            7.8              0.88         0.00             2.6   
2           3            7.8              0.76         0.04             2.3   
3           4           11.2              0.28         0.56             1.9   
4           5            7.4              0.70         0.00             1.9   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [3]:
array=D1.values
X=array[:,1:12]
y=array[:,12]

In [4]:
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [5]:
y

array([5., 5., 5., ..., 6., 5., 6.])

In [ ]:

#Try to select features from 11 'x' fields from sklearn.linear_model import LogisticRegression

In [33]:
# The above method is manual as we define precision=3
# Now above proceure can be done manually by using OLS as follows:

from sklearn.feature_selection import RFE  #(RFE- Recursive Forward Elemination)
from sklearn.linear_model import LogisticRegression
# OLs model is best as it utomatically gives bests fields based on p values

In [9]:
X1=sm.add_constant(X)  # X is Defined above which is fields except outcomes 

X1


array([[ 1.   ,  7.4  ,  0.7  , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 1.   ,  7.8  ,  0.88 , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 1.   ,  7.8  ,  0.76 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 1.   ,  6.3  ,  0.51 , ...,  3.42 ,  0.75 , 11.   ],
       [ 1.   ,  5.9  ,  0.645, ...,  3.57 ,  0.71 , 10.2  ],
       [ 1.   ,  6.   ,  0.31 , ...,  3.39 ,  0.66 , 11.   ]])

In [10]:
model=sm.OLS(y,X1).fit()

In [34]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.361
Model:                            OLS   Adj. R-squared:                  0.356
Method:                 Least Squares   F-statistic:                     81.35
Date:                Wed, 11 Sep 2019   Prob (F-statistic):          1.79e-145
Time:                        18:24:13   Log-Likelihood:                -1569.1
No. Observations:                1599   AIC:                             3162.
Df Residuals:                    1587   BIC:                             3227.
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         21.9652     21.195      1.036      0.300     -19.607      63.538
x1             0.0250      0.026      0.963      0.336      -0.026       0.076
x2            -1.0836      0.121     -8.948      0.000      -1.321      -0.846
x3            -0.1826      0.147     -1.240      0.215      -0.471       0.106
x4             0.0163      0.015      1.089      0.276      -0.013       0.046
x5            -1.8742      0.419     -4.470      0.000      -2.697      -1.052
x6             0.0044      0.002      2.009      0.045       0.000       0.009
x7            -0.0033      0.001     -4.480      0.000      -0.005      -0.002
x8           -17.8812     21.633     -0.827      0.409     -60.314      24.551
x9            -0.4137      0.192     -2.159      0.031      -0.789      -0.038
x10            0.9163      0.114      8.014      0.000       0.692       1.141
x11            0.2762      0.026     10.429      0.000       0.224       0.328
==============================================================================
Omnibus:                       27.376   Durbin-Watson:                   1.757
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               40.965
Skew:                          -0.168   Prob(JB):                     1.27e-09
Kurtosis:                       3.708   Cond. No.                     1.13e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.13e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
# If we apply classifiers on whole 11 fields wihtout feature selection by OLS then accuracy is 68% as shown in below code :summary()

In [12]:
from sklearn.model_selection import train_test_split
(X_train, X_test, y_train, y_test) =train_test_split(X,y,test_size=0.25,random_state=0) # random state=0 means it starts from index 0

In [13]:
classifier=LogisticRegression(random_state=0)

In [14]:
classifier.fit(X_train,y_train)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [15]:
y_pred=classifier.predict(X_test)

In [16]:
y_pred

array([6., 5., 6., 5., 6., 5., 5., 6., 5., 5., 5., 5., 6., 5., 6., 6., 7.,
       6., 6., 5., 6., 5., 6., 5., 5., 5., 5., 6., 5., 6., 6., 6., 6., 5.,
       6., 6., 5., 5., 6., 6., 5., 6., 7., 6., 6., 5., 6., 6., 5., 6., 5.,
       5., 6., 6., 5., 5., 5., 5., 6., 5., 5., 6., 6., 6., 5., 6., 5., 6.,
       6., 6., 5., 5., 5., 5., 5., 6., 5., 5., 5., 6., 5., 5., 6., 6., 6.,
       5., 6., 5., 5., 5., 5., 5., 6., 5., 6., 5., 6., 5., 5., 6., 7., 6.,
       6., 6., 5., 5., 5., 5., 6., 5., 6., 5., 6., 5., 6., 6., 6., 6., 6.,
       6., 5., 6., 6., 5., 6., 6., 5., 5., 6., 6., 5., 5., 6., 6., 6., 5.,
       6., 5., 6., 5., 6., 5., 6., 5., 6., 6., 6., 6., 6., 5., 6., 6., 5.,
       6., 6., 6., 5., 5., 6., 6., 6., 6., 6., 5., 6., 5., 6., 6., 5., 6.,
       6., 5., 5., 7., 6., 6., 7., 7., 6., 5., 5., 7., 5., 6., 7., 5., 6.,
       6., 5., 6., 6., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 5., 5.,
       5., 5., 5., 6., 6., 5., 6., 5., 5., 7., 5., 5., 6., 6., 6., 5., 5.,
       6., 6., 6., 5., 6.

In [17]:
from sklearn.metrics import accuracy_score

In [18]:
accuracy_score(y_test,y_pred)

0.6225

In [19]:
# Now lets apply selected featured fields and apply classifiers and lets see result


X2=D1[['volatile.acidity','chlorides','free.sulfur.dioxide','total.sulfur.dioxide','pH','sulphates','alcohol']]

In [20]:
X2

volatile.acidity  chlorides  free.sulfur.dioxide  total.sulfur.dioxide  \
0                0.700      0.076                 11.0                  34.0   
1                0.880      0.098                 25.0                  67.0   
2                0.760      0.092                 15.0                  54.0   
3                0.280      0.075                 17.0                  60.0   
4                0.700      0.076                 11.0                  34.0   
5                0.660      0.075                 13.0                  40.0   
6                0.600      0.069                 15.0                  59.0   
7                0.650      0.065                 15.0                  21.0   
8                0.580      0.073                  9.0                  18.0   
9                0.500      0.071                 17.0                 102.0   
10               0.580      0.097                 15.0                  65.0   
11               0.500      0.071                 17.0                 102.0   
12               0.615      0.089                 16.0                  59.0   
13               0.610      0.114                  9.0                  29.0   
14               0.620      0.176                 52.0                 145.0   
15               0.620      0.170                 51.0                 148.0   
16               0.280      0.092                 35.0                 103.0   
17               0.560      0.368                 16.0                  56.0   
18               0.590      0.086                  6.0                  29.0   
19               0.320      0.341                 17.0                  56.0   
20               0.220      0.077                 29.0                  60.0   
21               0.390      0.082                 23.0                  71.0   
22               0.430      0.106                 10.0                  37.0   
23               0.490      0.084                  9.0                  67.0   
24               0.400      0.085                 21.0                  40.0   
25               0.390      0.080                 11.0                  23.0   
26               0.410      0.080                  4.0                  11.0   
27               0.430      0.106                 10.0                  37.0   
28               0.710      0.080                 14.0                  35.0   
29               0.645      0.082                  8.0                  16.0   
...                ...        ...                  ...                   ...   
1569             0.510      0.056                 15.0                  34.0   
1570             0.360      0.230                 19.0                  35.0   
1571             0.380      0.038                 15.0                  25.0   
1572             0.690      0.069                 35.0                 104.0   
1573             0.580      0.075                 15.0                  50.0   
1574             0.310      0.074                 23.0                  92.0   
1575             0.520      0.060                 12.0                  20.0   
1576             0.300      0.081                 16.0                  29.0   
1577             0.700      0.076                 13.0                  27.0   
1578             0.670      0.118                 13.0                  20.0   
1579             0.560      0.053                 24.0                  32.0   
1580             0.350      0.068                  9.0                  26.0   
1581             0.560      0.053                 24.0                  32.0   
1582             0.715      0.053                 13.0                  27.0   
1583             0.460      0.074                 32.0                  98.0   
1584             0.320      0.061                 24.0                  34.0   
1585             0.390      0.066                 22.0                  48.0   
1586             0.310      0.065                 34.0                  60.0   
1587  

In [21]:
from sklearn.model_selection import train_test_split
(X_train, X_test, y_train, y_test) =train_test_split(X2,y,test_size=0.25,random_state=0) # random state=0 means it starts from index 0

In [22]:
## To increse the accuracy add std. scalar steps. Step to increase the accuracy are as follows
#Step 1:
from sklearn.preprocessing import StandardScaler


In [23]:
#Step 2:
sc=StandardScaler()

In [24]:
#Step 3:
x_train=sc.fit_transform(X_train)


In [25]:
#Step 4:
x_test=sc.transform(X_test)


In [26]:
classifier=LogisticRegression(random_state=0)

In [27]:
classifier.fit(x_train,y_train)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [28]:
y_pred=classifier.predict(x_test)


In [29]:
y_pred

array([6., 5., 6., 5., 6., 5., 5., 6., 5., 5., 5., 5., 6., 5., 6., 6., 7.,
       6., 6., 5., 6., 5., 6., 5., 5., 5., 5., 6., 5., 6., 6., 6., 6., 5.,
       6., 6., 5., 5., 6., 6., 5., 6., 7., 6., 6., 5., 5., 6., 5., 6., 5.,
       5., 6., 6., 6., 5., 5., 5., 6., 5., 5., 6., 6., 6., 5., 6., 5., 6.,
       6., 6., 5., 5., 5., 5., 5., 6., 5., 5., 5., 6., 5., 5., 6., 6., 5.,
       5., 6., 5., 5., 5., 5., 5., 6., 5., 6., 5., 6., 5., 5., 6., 7., 6.,
       6., 6., 6., 5., 6., 5., 6., 5., 6., 5., 6., 5., 6., 6., 6., 6., 6.,
       6., 5., 6., 5., 5., 6., 6., 5., 5., 6., 6., 5., 5., 6., 6., 6., 5.,
       6., 5., 6., 5., 6., 5., 5., 5., 6., 6., 6., 6., 6., 5., 6., 6., 5.,
       5., 6., 5., 5., 5., 6., 6., 6., 5., 6., 5., 6., 5., 6., 6., 5., 6.,
       6., 5., 5., 7., 6., 6., 6., 7., 6., 5., 5., 7., 5., 6., 7., 5., 6.,
       6., 5., 6., 6., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 5., 5.,
       5., 5., 5., 6., 6., 5., 6., 5., 5., 6., 5., 5., 6., 6., 5., 5., 5.,
       6., 6., 5., 5., 6.

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(y_test,y_pred)

0.6125

In [32]:
#By applying 4 tests still we are not getting accuracy so to check how much difference is there in predictions by following function
classifier.predict([[0.280,0.092,35.0,103.0,3.30,0.75,10.5]])


array([5.])